name: Deploy to Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.prod.yml build
        
    - name: Test Docker setup
      run: |
        docker-compose -f docker-compose.prod.yml config
        
    - name: Deploy to Railway (if main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Ready for Railway deployment!"
        echo "Go to railway.app and connect this repository"
